# Stop target ec2 instances and mark them for deletion.
# No dependency on ec2.py or ec2.ini

- hosts: localhost 
  name: Shutdown
  gather_facts: false

  tasks:
  - ec2_instance_facts:
      filters:
        "tag:Name": "{{ tag_name }}"
      region: "{{ region }}"
    register: ec2_facts

  - name: stopping instances 
    ec2:
      region: "{{ region }}"
      instance_id: "{{ item.instance_id }}"
      state: stopped
      wait: true
    loop: "{{ ec2_facts.instances }}"

  - name: marking instances for deletion
    ec2_tag:
      resource: "{{ item.instance_id }}"
      region: "{{ region }}"
      state: present 
      tags:
        Name: "terminate"
    loop: "{{ ec2_facts.instances }}"
