# WIP
- hosts: localhost 
  name: Shutdown
  gather_facts: false

  tasks:
  - ec2_instance_facts:
      filters:
        "tag:Name": "{{ tag_name }}"
      region: "{{ region }}"
    register: ec2_facts

  - debug: "msg={{ ec2_facts }}"

  - name: stopping instances 
    ec2:
      region: "{{ region }}"
      instance_id: "{{ item.instance_id }}"
      state: stopped
      wait: true
    loop: "{{ ec2_facts.instances }}"

  - name: untagging instances
    ec2_tag:
      resource: "{{ item.instance_id }}"
      region: "{{ region }}"
      state: list
      tags:
        Name: "terminate"
    loop: "{{ ec2_facts.instances }}"
